= Implementation notes

== Core entities inspect
- Attempted `cargo test --test inspect_api_sketch` before any accepted `insta` snapshot existed. It compiled and produced `tests/snapshots/inspect_api_sketch__inspect_api_sketch_snapshot_is_stable.snap.new`, then failed because the snapshot was unreviewed. Correct approach: accept the generated snapshot with `INSTA_UPDATE=always cargo test --test inspect_api_sketch`, then rerun the focused test normally.
- PR #57 review follow-up: `docs/api-sketch.typ` is an aspirational API sketch, so it can show the intended `#let nav = publisher.scope(...)` / `#nav.suppress()` shape even while the milestone parser only implements `publisher.nav.suppress()`. Parser call dispatch now routes exact `publisher.*` calls through a `PublisherCallHandler` trait boundary instead of a widening `match` over every supported call.
- PR #58 marker evaluation: attempted `cargo fetch` for embedded Typst dependencies inside the sandbox first; it failed DNS resolution for `index.crates.io`. Correct approach: rerun the same Cargo fetch with network approval, then keep `typst-kit` on `default-features = false` with `embed-fonts` only.
- PR #58 marker evaluation: tried representing `publisher.nav` as a Typst dictionary with a `suppress` function. Typst reported that dictionaries do not have a `suppress` method for `publisher.nav.suppress()`. Correct approach: put `suppress` in a small imported module and alias that module as `nav` from `publisher.typ`.
- PR #58 marker evaluation: full Typst evaluation initially made parser extraction depend on ordinary document rendering details, including invalid image fixture bytes and unresolved `@cite` references. Correct approach: use a parser-only Typst world that returns placeholder bytes for image files and sanitizes reference shorthand during marker evaluation while `typst-syntax` still extracts citations from the original source.
- PR #58 marker evaluation: imported support files such as `publisher.typ` were first reported as unreachable Typst source files. Correct approach: track Typst source imports during marker evaluation and exclude local publisher support files from publication-node reachability warnings.
