= Implementation notes

== Rendering milestone
- PRD-002 keeps rendering example-scoped: generate a reviewable Typst assembly from the parsed publication, then delegate PDF and HTML export to Typst libraries. Correct approach for this milestone is `typst-pdf` and the matching HTML exporter crate from Rust, not invoking the Typst CLI, query-engine evaluation, or final routed pages.
- PRD-002 review follow-up: the assembly artifact is a reviewable intermediate, not a requirement to hand-build Typst with strings. Correct approach is to preserve authored source content for reachable nodes, use Typst syntax/AST machinery where it helps, replace unimplemented projection output with explicit placeholders, and still persist the generated assembly so PDF and HTML exports share the same input.
- PRD-002 discussion correction: string-stitching should be treated as the wrong implementation model, not merely a less preferred one. Correct approach: build a structural assembly from Typst syntax/AST nodes or a narrow typed render IR, then serialize `.typ` only as an output artifact.
- PRD-002 export slice: attempted `cargo fetch` after adding `typst-pdf` in the sandbox first; it failed DNS resolution for `index.crates.io`. Correct approach: rerun the same `cargo fetch` with network approval, then keep `typst`, `typst-html`, `typst-pdf`, `typst-kit`, and `typst-syntax` on the aligned `0.14.2` Typst stack.
- PRD-002 export slice: first `cargo run --example api_sketch` failed at HTML compilation with `html export is only available when --features html is passed`. Correct approach for library use is to build the Typst `Library` with `Features::from_iter([Feature::Html])` in the render world before compiling `typst_html::HtmlDocument`.
- PRD-002 HTML correction: the single `api-sketch.html` inspect-style review document is the wrong target. Correct approach: keep `api-sketch.typ` and `api-sketch.pdf` as combined proof artifacts if useful, but compile one HTML document per reachable source node from transformed authored Typst source. Projection calls are replaced in-place with explicit placeholders for now; the current replacement is intentionally narrow to canonical `#publisher.outline`, `#publisher.bibliography`, `#publisher.ref`, and `#publisher.nav.suppress` calls, not alias or wrapper expansion.
- PRD-002 per-node HTML attempt: first focused render test failed because visible `@cite` placeholder text was still parsed as a Typst label reference, and the fixture PNG bytes failed HTML image decoding. Correct approach: render shorthand reference placeholders through `raw` text so Typst does not resolve them, and have the HTML render world return a valid placeholder image for image assets.
- PRD-002 inherited navigation correction: rendering only placeholders found at authored canonical calls missed inherited navigation projections on pages such as `writing.html`. Correct approach: emit remaining navigation projections as page-level placeholders before authored content, while still replacing authored projection calls in place.
- PRD-002 PDF/source correction: the old combined `api-sketch.typ` was an inspect-style assembly that diverged from per-node HTML. Correct approach: write generated per-node `.typ` files under `build/api-sketch/typst/`, compile each HTML page from its corresponding `.typ` file, and make `api-sketch.typ` a single-document PDF source that includes those same page `.typ` files with page breaks.
- PRD-002 regression assertion correction: first tightened test expected HTML quotes to be entity-encoded as `&quot;`, but Typst HTML emitted literal quotes inside the code block. Correct approach: assert the stable rendered text `scope="nav:index"` rather than an encoding form that the exporter does not produce here.

== Core entities inspect
- Attempted `cargo test --test inspect_api_sketch` before any accepted `insta` snapshot existed. It compiled and produced `tests/snapshots/inspect_api_sketch__inspect_api_sketch_snapshot_is_stable.snap.new`, then failed because the snapshot was unreviewed. Correct approach: accept the generated snapshot with `INSTA_UPDATE=always cargo test --test inspect_api_sketch`, then rerun the focused test normally.
- PR #57 review follow-up: `docs/api-sketch.typ` is an aspirational API sketch, so it can show the intended `#let nav = publisher.scope(...)` / `#nav.suppress()` shape even while the milestone parser only implements `publisher.nav.suppress()`. Parser call dispatch now routes exact `publisher.*` calls through a `PublisherCallHandler` trait boundary instead of a widening `match` over every supported call.
- PR #58 marker evaluation: attempted `cargo fetch` for embedded Typst dependencies inside the sandbox first; it failed DNS resolution for `index.crates.io`. Correct approach: rerun the same Cargo fetch with network approval, then keep `typst-kit` on `default-features = false` with `embed-fonts` only.
- PR #58 marker evaluation: tried representing `publisher.nav` as a Typst dictionary with a `suppress` function. Typst reported that dictionaries do not have a `suppress` method for `publisher.nav.suppress()`. Correct approach: put `suppress` in a small imported module and alias that module as `nav` from `publisher.typ`.
- PR #58 marker evaluation: full Typst evaluation initially made parser extraction depend on ordinary document rendering details, including invalid image fixture bytes and unresolved `@cite` references. Correct approach: use a parser-only Typst world that returns placeholder bytes for image files and sanitizes reference shorthand during marker evaluation while `typst-syntax` still extracts citations from the original source.
- PR #58 marker evaluation: imported support files such as `publisher.typ` were first reported as unreachable Typst source files. Correct approach: track Typst source imports during marker evaluation and exclude local publisher support files from publication-node reachability warnings.

== scoped rendering implementation
- Legacy strip (scoped rendering slice A): removed `Query`/`Projection` and all sub-enums from the model, the projection/query recorders, validators, and inspect/render formatters, plus the `legacy API sketch fixture` fixture and its tests. The scoped rendering fixture never exercised any of it (no `#publisher.outline/bibliography/ref/nav` calls), so the cut was mechanical. Approach that worked: delete bottom-up from `model.rs` and let the compiler enumerate every dead reference across `parser`, `validation`, `inspect`, and `render`. `src/parser/projections.rs` became `src/parser/scopes.rs` (only the publication-scope recorder survives). The render placeholder lowering (outline/bibliography/reference) was left compiling for now; it is replaced by real rendering in later slices.
- `ScopeKind` was trimmed to `Global`/`CurrentPage`/`Publication`; the old `Nav`/`Outline`/`Reference`/`Bibliography`/`Other` kinds were legacy scope-category behavior scoped rendering drops in favor of `tags:`.
- The `#in-scope(..ids)[..]` marker now decodes to `PublisherMarker::InScope` but records nothing during parsing; it is an authoring-time region context handled at render-entrypoint generation, not a graph edge or scope declaration.
- Real rendering (scoped rendering slices B-G): replaced the placeholder lowering with real scoped Typst. The single `RenderWorld` (promoted from the discovery harness) compiles either per-source HTML or a combined PDF; a `main`-overlay lets a generated entrypoint and its transformed `#include`s compile while imports/`.yml`/assets resolve against the real source tree.
- Bibliography consolidation confirmed against Typst 0.14.2: `#bibliography(("a.yml", "b.yml"))` accepts multiple sources and with `full: false` (default) lists only cited works. So an assembled PDF strips authored `#bibliography(...)` calls and emits exactly one consolidated call over the union of `.yml` paths; per-source HTML keeps each page's own single call. Probed live before implementing.
- Outline scope-bounding confirmed: `#outline(target: heading.where(level: 1).after(<scope-start-x>, inclusive: false).before(<scope-end-x>, inclusive: false))` lists only headings between the injected `#metadata(none) <scope-start-x>` / `<scope-end-x>` markers. The entrypoint wraps each contiguous run of same-scope sources in those markers.
- Cross-source references in the combined PDF: a native `@label` to an *unnumbered* heading fails paged compilation (`cannot reference heading without numbering`). Correct approach: in the assembled PDF, keep only *same-source* references native and lower every cross-source reference to display text (which also carries the `Title, Scope` context). In per-source HTML, same-source refs stay native and cross-source refs become `#link("route#label")[display]` with real prose display (no `#raw` wrapper).

== Selector/scope discovery
- scoped rendering fixture check: directly compiling nested source files such as `examples/discovery_site/writing/blog-2.typ` first failed with Typst access denied for `../publisher.typ`, because the CLI default project root is the source file directory. Correct approach for nested fixture checks is `typst compile --root examples/discovery_site ...`.
- scoped rendering HTML fixture check: `typst compile --format html ...` first failed because HTML export is feature-gated. Correct CLI approach is to pass `--features html`; Rust library worlds must build the `Library` with `Features::from_iter([Feature::Html])`.
- scoped rendering source-local reference check: compiling `writing/blog-2.typ` with the fixture root still failed because `@thesis-main` is outside that compiled source document. Current conclusion: ordinary Typst references need the target label in the compiled document; per-source HTML with cross-source references needs a publisher adapter such as generated reference/link stubs or another assembly strategy.
- scoped rendering discovery harness: first `cargo run --example discovery` failed because the local `CompileFailure` type did not implement `std::error::Error`, and `HeadingElem` level access was attempted through a field accessor without a `StyleChain`. Correct API approach is to implement `Display`/`Error` for the harness error and use `HeadingElem::resolve_level(StyleChain::default())` when inspecting heading levels.
- scoped rendering discovery harness: the next run built but failed at runtime searching for `/Users/jasoncairns/Development/my-site/index.typ`; graph entries are fixture-relative, while the Typst world expects repo-relative paths. Correct approach is to prefix fixture graph entries with `examples/discovery_site/` before compiling or introspecting them.
- scoped rendering selector probe: trying to use a `block` or `context` as a lexical query boundary still let `query(heading)` see headings outside the block. Correct conclusion: use the compiled Typst document as the default rendered-region boundary, or use explicit selectors such as `selector(heading).after(...).before(...)` for contiguous marker-bounded windows.
- scoped rendering reference probe: hidden-including a target source made an external label resolve, but the hidden heading and citations still polluted ordinary introspection and bibliography inputs. Correct conclusion: per-source HTML cross-source references need a real reference/link adapter, not hidden target inclusion.
- scoped rendering heading-promotion probe: a broad show-rule re-emitting headings hit maximum show-rule depth, and a narrowed rule produced both original and generated heading levels. Correct conclusion: scope heading promotion should be generated-source or AST work at the render entrypoint, not a Typst show-rule trick.
- scoped rendering counter probe: compiling `thesis/ch-01.typ` and `thesis/ch-02.typ` through one generated entrypoint rendered headings as `1.` and `2.` naturally, while compiling `ch-02.typ` alone rendered it as `1.`. Correct approach for cross-source numbering in per-source HTML is to provide counter seed/state at the start of the generated source, e.g. `#counter(heading).update(1)` before the second top-level heading so it renders as `2.` and nested headings as `2.1.`.
- scoped rendering reference probe: compiling a combined document containing `ch-01`, `ch-02`, and a blog reference rendered `@ch-02` as a normal link to `#ch-02` with display `Section 2`, while compiling the blog alone failed with missing label. Correct conclusion: scope/edition entrypoints can use native references when targets are present; per-source HTML needs a generated link/display adapter for external-source references.
- scoped rendering marker slice: first `cargo fmt --check` after adding focused parser assertions failed only because the new assertion wrapping was not rustfmt-formatted. Correct approach is to run `cargo fmt` after edits, then rerun `cargo fmt --check` before validation.
- scoped rendering scope validation slice: first `cargo fmt --check` after adding active-scope assertions failed only because the new assertion wrapping was not rustfmt-formatted. Correct approach remains to run `cargo fmt`, then rerun the focused test and `cargo fmt --check`.
- scoped rendering cross-source reference slice: first generated-reference adapter preserved native `@label` references in the combined PDF proof input. The focused test then failed paged compilation on unnumbered heading references. Correct approach for this slice is to preserve native refs only where the source-local HTML compilation can own the target, lower cross-source HTML refs to explicit links, and keep combined-PDF proof refs as explicit text until a later combined-entrypoint reference policy is implemented.
- scoped rendering scope-entrypoint slice: first compile after adding `render_pdf_source` as an iterator-generic helper passed `&Vec<&RenderSource>` and produced `&&RenderSource` items. Correct approach is to pass the `Vec<&RenderSource>` by value so the iterator item type is `&RenderSource`.

== Issue follow-up
- Issue #65 bare-root repro: running `publisher inspect --root index.typ scopes` from a temporary site directory failed as `error: : No such file or directory (os error 2)` because `Path::parent()` for a bare filename is an empty path, not `None`. Correct approach is to normalize an empty parent to `.` anywhere the root's source directory is derived.
- Issue #71 SVG repro: rendering a document with a valid `assets/Smiley.svg` failed during marker evaluation with `failed to parse SVG (file is not valid utf-8 ...)` because the parser world returned PNG placeholder bytes for every image extension. Correct approach for existing files is to read the real bytes in marker evaluation; placeholder fabrication is not format-invariant.
- Issue #66 PDF-name repro: rendering two independent roots to the same output directory wrote `publication.pdf` and `publication.typ` both times, so the second render overwrote the first. A first verification command tried GNU `find -printf`, which failed on macOS `find`; correct local check is `ls -1` or a portable `find ... -exec basename {} \;`.
